package com.briup.apps.pul.dao;

import com.briup.apps.pul.bean.Login;
import com.briup.apps.pul.bean.LoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    long countByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int deleteByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    List<Login> selectByExampleWithBLOBs(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    List<Login> selectByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    Login selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_login
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKey(Login record);
}