package com.briup.apps.pul.dao;

import com.briup.apps.pul.bean.Profile;
import com.briup.apps.pul.bean.ProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    long countByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int deleteByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int insert(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int insertSelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    List<Profile> selectByExampleWithBLOBs(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    List<Profile> selectByExample(ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    Profile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Profile record, @Param("example") ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Profile record, @Param("example") ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByExample(@Param("record") Profile record, @Param("example") ProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKeySelective(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Profile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pul_profile
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    int updateByPrimaryKey(Profile record);
}