package com.briup.apps.pul.bean;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_notice.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_notice.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private Long profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_notice.message
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_notice.id
     *
     * @return the value of pul_notice.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_notice.id
     *
     * @param id the value for pul_notice.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_notice.profile_id
     *
     * @return the value of pul_notice.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_notice.profile_id
     *
     * @param profileId the value for pul_notice.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_notice.message
     *
     * @return the value of pul_notice.message
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_notice.message
     *
     * @param message the value for pul_notice.message
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}