package com.briup.apps.pul.bean;

public class Option {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_option.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_option.name
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_option.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private Long profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pul_option.description
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_option.id
     *
     * @return the value of pul_option.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_option.id
     *
     * @param id the value for pul_option.id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_option.name
     *
     * @return the value of pul_option.name
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_option.name
     *
     * @param name the value for pul_option.name
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_option.profile_id
     *
     * @return the value of pul_option.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public Long getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_option.profile_id
     *
     * @param profileId the value for pul_option.profile_id
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setProfileId(Long profileId) {
        this.profileId = profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pul_option.description
     *
     * @return the value of pul_option.description
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pul_option.description
     *
     * @param description the value for pul_option.description
     *
     * @mbg.generated Thu Aug 09 14:47:37 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}